x-airflow-common: &airflow-common
  image: apache/airflow:3.1.8
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution/
    PYTHONPATH: /opt/airflow/src
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./src:/opt/airflow/src
    - ./sql:/opt/airflow/sql
    - ./data:/opt/airflow/data
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${AIRFLOW_PG_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_PG_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_PG_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create \
        --username ${AIRFLOW_USER} \
        --password ${AIRFLOW_PASSWORD} \
        --firstname admin \
        --lastname admin \
        --role Admin \
        --email admin@example.com
      "

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - '${AIRFLOW_WEBSERVER_PORT}:8080'
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always

volumes:
  postgres-db-volume: